# Application Configuration
server:
  #port: 8080
  port: 8092

  # ===============================================
  # Changes to the Default Error Page’s Content
  # The error message and any binding errors are no longer included in the default error page by default.
  # This reduces the risk of leaking information to a client. server.error.include-message and server.error.include-binding-errors can be used to control the inclusion of the message and binding errors respectively.
  # Supported values are always, on-param, and never.
  # ===============================================
  error:
    include-message: always

spring:
  # ===============================================
  # To See H2 Console in Browser:
  # http://localhost:8091/h2-console
  # Enabling H2 Console
  # ===============================================
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # ===============================================
  # JPA
  # ===============================================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  # ===============================================
  # DB
  # ===============================================
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platfom: h2
    username: sa
    password:

  cloud:
    config:
      enabled: false



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LAVEL_PATTERN:-%5P} %m%n"




